version: "3.3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wardrobe_db
      MYSQL_USER: wardrobe_user
      MYSQL_PASSWORD: wardrobe_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot" , "-pexample" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8084:80
    restart: always
